name: Docker Release

on:
  workflow_dispatch:
    inputs:
      docker_tags:
        type: string
        description: "Docker Tags"
        required: true
        default: "dev"

  push:
    branches:
      - master

jobs:
  build_and_push_docker:
    runs-on: ubuntu-latest
    env:
      release_arch: "linux/amd64,linux/arm64"
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest,enable=${{ github.event_name != 'workflow_dispatch' }}
            type=raw,value={{date 'YYYY-MM-DD'}},enable=${{ github.event_name != 'workflow_dispatch' }}
            type=raw,value={{sha}},enable=${{ github.event_name != 'workflow_dispatch' }}
            type=raw,value=${{ inputs.docker_tags }},enable=${{ github.event_name == 'workflow_dispatch' }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ env.release_arch }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
